<?php
require_once '../config/database.php';
requireLogin();

if (!hasRole('admin')) {
    header('Location: ../auth/login.php');
    exit();
}

$database = new Database();
$db = $database->getConnection();

// Lấy danh sách báo cáo admin
$query = "SELECT r.*, u.first_name, u.last_name FROM admin_reports r LEFT JOIN users u ON r.generated_by = u.id ORDER BY r.generated_at DESC LIMIT 100";
$stmt = $db->prepare($query);
$stmt->execute();
$reports = $stmt->fetchAll(PDO::FETCH_ASSOC);
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Reports - University LMS</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
    <link href="../assets/css/dashboard.css" rel="stylesheet">
</head>
<body>
    <?php include '../includes/admin_navbar.php'; ?>
    <div class="container-fluid">
        <div class="row">
            <?php include '../includes/admin_sidebar.php'; ?>
            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                    <h1 class="h2">
                        <i class="fas fa-chart-pie"></i> Admin Reports
                    </h1>
                </div>
                <div class="row mb-4">
                    <div class="col-12">
                        <div class="card bg-dark text-white">
                            <div class="card-body">
                                <h4><i class="fas fa-file-alt"></i> Report Viewer</h4>
                                <p class="mb-0">View reports generated by the system.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row mb-4">
                    <div class="col-12">
                        <div class="card shadow">
                            <div class="card-header py-3">
                                <h6 class="m-0 font-weight-bold text-primary">
                                    <i class="fas fa-list"></i> Reports List
                                </h6>
                            </div>
                            <div class="card-body table-responsive">
                                <table class="table table-bordered table-hover align-middle">
                                    <thead class="table-light">
                                        <tr>
                                            <th scope="col">#</th>
                                            <th scope="col">Report Type</th>
                                            <th scope="col">Title</th>
                                            <th scope="col">Description</th>
                                            <th scope="col">Created By</th>
                                            <th scope="col">Created At</th>
                                            <th scope="col">Status</th>
                                            <th scope="col">Details</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($reports as $report): ?>
                                            <tr>
                                                <td><?php echo $report['id']; ?></td>
                                                <td><?php echo htmlspecialchars($report['report_type']); ?></td>
                                                <td><?php echo htmlspecialchars($report['report_title']); ?></td>
                                                <td><?php echo htmlspecialchars($report['report_description']); ?></td>
                                                <td><?php echo isset($report['first_name']) ? htmlspecialchars($report['first_name'] . ' ' . $report['last_name']) : '<span class="text-muted">System</span>'; ?></td>
                                                <td><?php echo formatDate($report['generated_at']); ?></td>
                                                <td>
                                                    <?php
                                                        $status = $report['status'];
                                                        $badge = [
                                                            'pending' => 'bg-warning',
                                                            'completed' => 'bg-success',
                                                            'failed' => 'bg-danger'
                                                        ];
                                                    ?>
                                                    <span class="badge <?php echo $badge[$status]; ?> text-uppercase"> <?php echo ucfirst($status); ?> </span>
                                                </td>
                                                <td>
                                                    <?php if (!empty($report['report_data'])): ?>
                                                        <button class="btn btn-sm btn-info" type="button" data-bs-toggle="collapse" data-bs-target="#reportData<?php echo $report['id']; ?>">Xem</button>
                                                        <div class="collapse mt-2" id="reportData<?php echo $report['id']; ?>">
                                                            <pre class="bg-light p-2 border rounded small"><?php echo htmlspecialchars($report['report_data']); ?></pre>
                                                        </div>
                                                    <?php else: ?>
                                                        <span class="text-muted">No data available</span>
                                                    <?php endif; ?>
                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                                <?php if (count($reports) == 0): ?>
                                    <div class="alert alert-info">No reports found.</div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
